import { useState } from "react";
import { quickhacks } from "../data/quickhacks";
import { cyberdecks } from "../data/cyberdecks";
import { districtProgressionOrder } from "../data/districtProgressionOrder";
import { districts } from "../data/districts";
import { getItem } from "../data/items";
import { canCraftQuickhack, craftQuickhack, deckCapacity, equippedDeck, installedQuickhacks, installQuickhack, removeQuickhack, canBuySoftware, buySoftware, softwareStageUnlocked, quickhackRamCost, ramRecovery, deckBonuses } from "../systems/quickhackSystem";
import { equipItem } from "../systems/equipmentSystem";
import { meetsItemAttributeRequirement, itemAttributeRequirement } from "../systems/runnerProgression";
import { maxRam } from "../systems/rpgSystem";
import type { GameState } from "../types";
const stageLabel = (stage: number) => districts.find(d => d.id === districtProgressionOrder[stage])?.name ?? "Neon Row";
export function QuickhackPanel({ state, onUpdate }: { state: GameState; onUpdate: (fn: (s: GameState) => GameState) => void }) {
  const [rarity, setRarity] = useState("All"), [ownedOnly, setOwnedOnly] = useState(false);
  const deck = equippedDeck(state), installed = installedQuickhacks(state), locked = Boolean(state.rpg.active), bonuses = deckBonuses(state);
  const decks = Object.keys(state.inventory).map(getItem).filter(item => item && state.inventory[item.id] > 0 && deckCapacity(item) > 0);
  return <section className="stack netrunner-library" aria-label="Cyberdeck and quickhacks">
    <article className="panel"><p className="eyebrow">NETRUNNER / ACTIVE LOADOUT</p><h2>{deck?.name ?? "Equip a cyberdeck"}</h2><p>Install one version of each program family. Installing another rarity replaces that family's installed version without consuming either program. Each deck remembers its loadout.</p>
    <div className="runner-vitals"><span>RAM CAPACITY<strong>{maxRam(state)}</strong></span><span>PROGRAM SLOTS<strong>{installed.length} / {deckCapacity(deck)}</strong></span><span>RAM PER TURN<strong>{ramRecovery(state)}</strong></span><span>DECK DAMAGE BONUS<strong>+{Math.round(bonuses.damage * 100)}%</strong></span></div>
    <p className="muted">RAM refills for each enemy. Recover RAM grants 3 extra RAM while taking cover. Deck and perk discounts are reflected in cast costs below.</p>
    {locked && <p className="rpg-choice-warning">Return to the clinic before changing your deck, buying, crafting, or installing programs.</p>}
    <div className="inventory-filter-row">{decks.map(item => item && <button key={item.id} disabled={locked || !meetsItemAttributeRequirement(state, item)} title={itemAttributeRequirement(item).label} aria-pressed={deck?.id === item.id} className={deck?.id === item.id ? "active" : ""} onClick={() => onUpdate(s => equipItem(s, item.id))}>{item.name} / {item.rarity} / {deckCapacity(item)} slots</button>)}</div>
    {!decks.length && <p className="muted">Claim your field kit in Missions for an Entry Cyberdeck and two installed programs.</p>}
    <div className="program-slot-grid">{Array.from({ length: deckCapacity(deck) }, (_, index) => { const hack = installed[index]; return <div className="program-slot" key={index}><small>SLOT {index + 1}</small>{hack ? <><b>{hack.name}</b><span className={`software-rarity rarity-${hack.rarity.toLowerCase()}`}>{hack.rarity} / {quickhackRamCost(state, hack)} RAM</span><button disabled={locked} onClick={() => onUpdate(s => removeQuickhack(s, hack.id))}>Remove</button></> : <span>Empty program slot</span>}</div>; })}</div>
    </article>
    <article className="panel"><p className="eyebrow">HARDWARE / CYBERDECK EXCHANGE</p><h2>Cyberdecks</h2><p>Main jobs award district decks for free. Buy one after reaching its district, or replay local gigs for replacements. New decks are usable immediately; equip and install programs between missions.</p><div className="software-grid">{cyberdecks.map(entry => <article className="software-card" key={entry.id}><span className={`software-rarity rarity-${entry.rarity.toLowerCase()}`}>{entry.rarity}</span><h3>{entry.name}</h3><p>{entry.description}</p><div className="software-specs"><span>{entry.slots} slots</span><span>+{entry.ram} base RAM</span><span>+{Math.round(entry.damage * 100)}% hack damage</span><span>+{entry.recovery} RAM/turn</span>{entry.discount > 0 && <span>-{entry.discount} RAM/cast</span>}</div><p className="muted">Source: {stageLabel(entry.stage)} main job or local gig.</p><button disabled={!canBuySoftware(state, entry.id)} onClick={() => onUpdate(s => buySoftware(s, entry.id))}>{state.inventory[entry.id] > 0 ? "Owned" : !softwareStageUnlocked(state, entry.stage) ? `Reach ${stageLabel(entry.stage)}` : `Buy / ${entry.price.toLocaleString()} credits`}</button></article>)}</div></article>
    <article className="panel"><p className="eyebrow">SOFTWARE / LIBRARY & CRAFTING</p><h2>Quickhacks</h2><p className="muted">Buy programs with credits or craft them with Technical and Encrypted Data. Reaching a district opens its stock; main jobs and rotating local-gig rewards also provide programs. Your field kit includes Short Circuit and Reboot Optics.</p>
    <div className="software-filter"><label>Rarity <select value={rarity} onChange={event => setRarity(event.target.value)}>{["All", "Common", "Uncommon", "Rare", "Epic", "Legendary"].map(value => <option key={value}>{value}</option>)}</select></label><label><input type="checkbox" checked={ownedOnly} onChange={event => setOwnedOnly(event.target.checked)} /> Owned only</label><span>{state.resources.credits.toLocaleString()} credits / {state.resources.encryptedData.toLocaleString()} Encrypted Data</span></div>
    <div className="software-grid">{quickhacks.filter(h => (rarity === "All" || h.rarity === rarity) && (!ownedOnly || state.inventory[h.id] > 0)).map(h => {
      const owned = state.inventory[h.id] > 0, active = installed.some(i => i.id === h.id), replaces = installed.some(i => i.family === h.family), full = installed.length >= deckCapacity(deck) && !replaces;
      return <article className={`software-card ${active ? "installed" : ""}`} key={h.id}><span className={`software-rarity rarity-${h.rarity.toLowerCase()}`}>{h.rarity} / {quickhackRamCost(state, h)} RAM</span><h3>{h.name}</h3><p>{h.description}</p><p className="muted">Source: {stageLabel(h.stage)} exchange, main job or local gig.</p><p>Craft: {h.cost.credits} credits + {h.cost.encryptedData} Encrypted Data / Technical {h.technical}</p><div className="software-actions"><button disabled={!canBuySoftware(state, h.id)} onClick={() => onUpdate(s => buySoftware(s, h.id))}>{owned ? "Owned" : `Buy / ${h.price.toLocaleString()} credits`}</button><button disabled={!canCraftQuickhack(state, h.id)} onClick={() => onUpdate(s => craftQuickhack(s, h.id))}>Craft program</button><button disabled={locked || !owned || !deck || (!active && full)} onClick={() => onUpdate(s => active ? removeQuickhack(s, h.id) : installQuickhack(s, h.id))}>{active ? "Remove from deck" : !deck ? "Equip a cyberdeck first" : replaces ? "Replace installed version" : full ? "Deck full" : "Install on deck"}</button></div>{!softwareStageUnlocked(state, h.stage) && <p className="rpg-choice-warning">Reach {stageLabel(h.stage)} to buy or craft.</p>}</article>;
    })}</div>{ownedOnly && !quickhacks.some(h => state.inventory[h.id] > 0 && (rarity === "All" || h.rarity === rarity)) && <p>No owned programs match this rarity.</p>}
    </article>
  </section>;
}
