import { gigRisks, gigPayout, heatCleanupCost, clearHeatWithFixer } from "../systems/rpgSystem";
import { equippedDeck, installedQuickhacks } from "../systems/quickhackSystem";
import { NetworkHero } from "./NetworkHero";
import { playerCombatStats } from "../systems/formulas";
import { useState, type ReactNode } from "react";
import { ArrowRight, ArrowUpRight, Backpack, TrendingUp, Check, ChevronRight, Cpu, Crosshair, HeartPulse, LockKeyhole, MapPin, MessageSquare, Radio, Shield, Skull, Sparkles, Target, Terminal, UserRound, Zap } from "lucide-react";
import { attributeDefinitions, rpgMissions, rpgSideGigs, rpgPerks, type RpgMission } from "../data/rpgCampaign";
import { districts } from "../data/districts";
import { getItem } from "../data/items";
import { calculateMaxHP } from "../systems/healthSystem";
import { approachRequirement, campaignEpilogue, fieldInjectorCount, buyRpgPerk, canUseTactic, chooseMissionApproach, claimFieldKit, enemyIntent, leaveRpgMission, mainChaptersCleared, maxRam, missionAvailable, missionById, performTactic, resolveRpgMission, respecRpg, retryRpgMission, rpgXpNeeded, spendAttribute, startRpgMission, tacticalStats } from "../systems/rpgSystem";
import type { GameState } from "../types";
import type { MissionApproach, TacticalAction, GigRisk } from "../rpgTypes";
import "./rpg.css";

type Update = (fn: (state: GameState) => GameState) => void;
const approachNames: Record<MissionApproach, string> = { assault: "Kick the door", ghost: "Go in quiet", netrunner: "Own the network", lifepath: "Use your connections" };
const endingNames: Record<string, string> = { free: "A City of Voices", own: "The New Sovereign", erase: "A Beautiful Silence" };

export type MainSection = "journal" | "character" | "progress" | "intel";

export function RpgHub({ state, onUpdate, onServices, page, onPage: setPage, inventoryNoticeCount = 0, children }: { state: GameState; onUpdate: Update; onServices: () => void; page: MainSection; onPage: (page: MainSection) => void; inventoryNoticeCount?: number; children?: ReactNode }) {
  const [gigs, setGigs] = useState(false);
  const [gigRisk, setGigRisk] = useState<GigRisk>("standard");
  const [selected, setSelected] = useState(() => rpgMissions.find(m => !state.rpg.completed[m.id])?.id ?? rpgMissions[7].id);
  const active = state.rpg.active;
  const mission = (active ? missionById(active.missionId) : missionById(selected)) ?? rpgMissions[0];
  const next = rpgMissions.find(m => !state.rpg.completed[m.id]);
  const completed = mainChaptersCleared(state);
  const kit = state.rpg.starterClaimed;
  const selectedRisk = active?.gigRisk ?? ((state.rpg.completed[mission.id]?.clears ?? 0) >= gigRisks[gigRisk].clears ? gigRisk : "standard");
  return <section className="rpg-shell" aria-label="Main / Afterimage RPG">
    <NetworkHero title={["NEON", "AFTERIMAGE"]} eyebrow="YOUR NAME. YOUR RULES. YOUR CONSEQUENCES." description={<>Build a reputation. Bend the network.<br />Decide what survives the night.</>} status={<>PROFILE {String(state.rpg.level).padStart(2, "0")} <i /> STREET CRED {state.rpg.streetCred}</>} progress={{ label: "AFTERIMAGE / MAIN STORY", value: completed, maximum: 8, suffix: "/08", note: active ? "FIELD CONNECTION ACTIVE" : next ? `NEXT SIGNAL: ${next.fixer.toUpperCase()}` : "CAMPAIGN COMPLETE" }} actions={<><button className="rpg-primary" onClick={() => { setPage("journal"); setGigs(false); setSelected(next?.id ?? rpgMissions[7].id); }}>{active ? "Return to mission" : next ? "Track next lead" : "Review your ending"}<ArrowUpRight size={17} /></button><button className="rpg-text-button" onClick={() => setPage("character")}>Manage character <ChevronRight size={15} /></button></>} />
    <div className="rpg-section-nav" role="tablist" aria-label="Runner network sections">{([['journal','Missions',MessageSquare],['character','Character',UserRound],['progress','Progress',TrendingUp],['intel','Field manual',Terminal]] as const).map(([id,label,Icon]) => <button role="tab" aria-selected={page === id} key={id} onClick={() => setPage(id)} className={page === id ? "selected" : ""}><Icon size={16} />{label}{id === "character" && state.rpg.attributePoints + state.rpg.perkPoints > 0 && <b>{state.rpg.attributePoints + state.rpg.perkPoints}</b>}{id === "character" && inventoryNoticeCount > 0 && <b aria-label={`${inventoryNoticeCount} inventory updates`}>{inventoryNoticeCount} new</b>}</button>)}<button className="rpg-services" onClick={onServices}>District services <ArrowUpRight size={15} /></button></div>
    {page === "journal" && kit && <div className="rpg-kit"><div><p className="rpg-eyebrow">FIXER SERVICES / HEAT {Math.ceil(state.resources.heat)}</p><p>Local gigs pay every clear and remove 15 Heat. For immediate cleanup, pay your fixer 10 credits per Heat.</p></div><button className="rpg-primary" disabled={Boolean(active) || state.resources.heat <= 0 || state.resources.credits < heatCleanupCost(state)} onClick={() => onUpdate(clearHeatWithFixer)}>Clear Heat / {heatCleanupCost(state)} credits</button></div>}
    {!kit && page === "journal" && <div className="rpg-kit"><Cpu size={28} /><div><h2>Your first call is waiting.</h2><p>Sable left a sidearm, armor, medicine, and a rechargeable quickhack deck. Claim the kit to begin. Existing equipment is kept.</p></div><button className="rpg-primary" onClick={() => onUpdate(claimFieldKit)}>Claim field kit <ArrowRight size={16} /></button></div>}
    {page !== "journal" && page !== "intel" ? <div className="main-section-content">{children}</div> : page === "intel" ? <FieldManual /> : <div className="rpg-journal">
      <aside className="rpg-quest-list"><div className="rpg-list-heading"><span>YOUR JOURNAL</span><b>{completed}/8</b></div><div className="rpg-list-filters"><button className={!gigs ? "selected" : ""} onClick={() => { setGigs(false); if (!active) setSelected(next?.id ?? rpgMissions[7].id); }}>Main jobs</button><button className={gigs ? "selected" : ""} onClick={() => { setGigs(true); if (!active) { setSelected((rpgSideGigs.find(m => missionAvailable(state, m)) ?? rpgSideGigs[0]).id); setGigRisk("standard"); } }}>Local gigs</button></div>
        {(gigs ? rpgSideGigs : rpgMissions).map(m => {
          const done = state.rpg.completed[m.id], available = missionAvailable(state, m), current = m.id === mission.id;
          return <button key={m.id} className={`rpg-quest ${current ? "selected" : ""}`} onClick={() => { setSelected(m.id); setGigRisk("standard"); }} disabled={Boolean(active && active.missionId !== m.id)} aria-current={current ? "true" : undefined}>
            <span className="rpg-quest-number">{done && !m.sideGig ? <Check size={16} /> : !available && !done ? <LockKeyhole size={14} /> : String(m.act + 1).padStart(2,"0")}</span><span><small>{districts.find(d => d.id === m.district)?.name}</small><strong>{m.title}</strong><em>{done ? m.sideGig ? `${done.clears} completed / replayable` : "Completed" : available ? m.sideGig ? "Gig available" : "Lead available" : m.act === 0 ? "Claim your field kit" : `Finish ${rpgMissions[m.act - 1].title}`}</em></span><ChevronRight size={14} /></button>;
        })}
        <p className="rpg-list-note">Main jobs unlock the next district. Local gigs build XP and credits. Idle training is optional for this campaign.</p>
      </aside>
      <div className="rpg-mission-content"><div className="rpg-mission-heading"><p className="rpg-eyebrow">{mission.sideGig ? "FIXER GIG" : `MAIN JOB / ACT ${String(mission.act + 1).padStart(2,"0")}`}</p><h2>{mission.title}</h2><p>{mission.tagline}</p><span><MapPin size={13} />{mission.location}</span></div>
        {active?.phase === "combat" ? <TacticalEncounter state={state} mission={mission} onUpdate={onUpdate} /> : active?.phase === "failed" ? <div className="rpg-failed"><Skull size={42} /><h3>Flatlined. Not forgotten.</h3><p>Your fixer got you out. Retry with full health and fresh field injectors, or return to change your build. No credits or equipment are lost.</p><div className="rpg-button-row"><button className="rpg-primary" onClick={() => onUpdate(retryRpgMission)}>Retry mission</button><button onClick={() => onUpdate(leaveRpgMission)}>Return to clinic</button></div></div> : active?.phase === "decision" ? <div className="rpg-decision"><div className="rpg-contact"><MessageSquare size={20} /><span>SECURE CALL / {mission.fixer.toUpperCase()}</span></div><h3>The job is done. The choice is yours.</h3><p>{mission.reveal}</p><span className="rpg-choice-warning">{mission.sideGig ? "Confirm the extraction to collect your rewards." : "This decision is permanent for this save and recorded in your journal."}</span><div className="rpg-choices">{mission.choices.map(choice => <button key={choice.id} onClick={() => onUpdate(s => resolveRpgMission(s, choice.id))}><span><strong>{choice.label}</strong><small>{choice.detail}</small></span><ArrowUpRight size={20} /></button>)}</div></div> : <>
          <div className="rpg-contact"><span className="rpg-contact-avatar">{mission.fixer.split(" ").map(n => n[0]).join("")}</span><div><small>INCOMING / ENCRYPTED</small><strong>{mission.fixer}</strong></div><Radio size={18} /></div><p className="rpg-briefing">“{mission.briefing}”</p>
          {state.rpg.completed[mission.id] && !active && <div className="rpg-aftermath"><Check size={19} /><div><h3>{mission.act === 7 && !mission.sideGig && state.rpg.ending ? endingNames[state.rpg.ending] : "Job closed"}</h3><p>{mission.choices.find(c => c.id === state.rpg.completed[mission.id].outcome)?.response}</p><small>Approach: {approachNames[state.rpg.completed[mission.id].approach]}</small>{mission.act === 7 && !mission.sideGig && <p>{rpgMissions.slice(0,7).filter(m => state.rpg.completed[m.id]?.outcome === "protect").length} of your 7 earlier decisions protected the people caught in the program. {campaignEpilogue(state)}</p>}</div></div>}
          <div className="rpg-objective"><Target size={19} /><div><small>OBJECTIVE</small><strong>{mission.objective}</strong></div></div>
          {mission.sideGig && !active && <div className="stack"><p className="rpg-eyebrow">REPLAY CONTRACT / {state.rpg.completed[mission.id]?.clears ?? 0} CLEARS</p><div className="rpg-button-row">{(Object.keys(gigRisks) as GigRisk[]).map(risk => <button key={risk} aria-pressed={selectedRisk === risk} disabled={(state.rpg.completed[mission.id]?.clears ?? 0) < gigRisks[risk].clears} onClick={() => setGigRisk(risk)}>{gigRisks[risk].label} / {gigRisks[risk].payout}x credits{gigRisks[risk].clears > 0 ? " / " + gigRisks[risk].clears + " clears required" : ""}</button>)}</div><p className="muted">Enemy health x{gigRisks[selectedRisk].health}; enemy damage x{gigRisks[selectedRisk].damage}. Supplies and XP stay the same. Main jobs alone advance the Afterimage story.</p></div>}<div className="rpg-reward-strip"><span>CONTRACT VALUE <b>€$ {gigPayout(mission, selectedRisk).toLocaleString()}</b></span><span>CHARACTER XP <b>{state.rpg.completed[mission.id] && mission.sideGig ? Math.round(mission.xp * .5) : mission.xp}</b></span><span>SUPPLIES <b>{mission.sideGig ? "1 rotating component" : "+ Guaranteed weapon"}</b></span></div>
          {active?.phase === "briefing" ? <><h3 className="rpg-subheading">Choose your way in</h3><div className="rpg-approaches">{(["assault","ghost","netrunner","lifepath"] as MissionApproach[]).map(approach => { const req = approachRequirement(state,mission,approach); return <button key={approach} disabled={!req.met} onClick={() => onUpdate(s => chooseMissionApproach(s, approach))}><span>{approach === "netrunner" ? <Cpu size={21} /> : approach === "ghost" ? <Shield size={21} /> : approach === "lifepath" ? <MessageSquare size={21} /> : <Crosshair size={21} />}</span><strong>{approachNames[approach]}</strong><small>{req.label}</small>{approach === "lifepath" && <small>{mission.pathLine}</small>}</button>; })}</div><button className="rpg-text-button" onClick={() => onUpdate(leaveRpgMission)}>Leave briefing and change build</button></> : <button className="rpg-primary rpg-start" disabled={!missionAvailable(state,mission)} onClick={() => onUpdate(s => startRpgMission(s,mission.id,selectedRisk))}>{state.rpg.completed[mission.id] && !mission.sideGig ? "Chapter completed" : !kit ? "Claim the field kit first" : missionAvailable(state,mission) ? mission.sideGig ? "Accept gig" : "Answer the call" : "Complete the previous main job"}<ArrowUpRight size={19} /></button>}
          <p className="rpg-mission-note">Fixer support restores health before deployment and supplies {fieldInjectorCount(state)} field injectors. Starting a mission stops idle work. Combat advances only when you choose an action.</p>
        </>}
      </div>
    </div>}
  </section>;
}

function TacticalEncounter({ state, mission, onUpdate }: { state: GameState; mission: RpgMission; onUpdate: Update }) {
  const e = state.rpg.active!, stats = tacticalStats(state), maxHp = calculateMaxHP(state);
  const moves: Array<{ id: TacticalAction; name: string; detail: string; Icon: typeof Target }> = [
    { id:"attack",name:e.aimed ? "Aimed shot" : "Fire weapon", detail:`${stats.damage} base damage${e.aimed ? " · aim bonus ready" : ""}`,Icon:Crosshair },
    { id:"aim",name:"Aim from cover",detail:"Prime next shot · reduce incoming damage",Icon:Target },
    { id:"cover",name:"Take cover",detail:"Absorb a burst · regenerate RAM",Icon:Shield },
    ...installedQuickhacks(state).map(h => ({ id: h.action, name: h.name, detail: h.ram + " RAM / " + Math.round(stats.hack * h.multiplier * (e.approach === "netrunner" ? 1.35 : 1)) + " damage" + (h.interrupt ? " / interrupts" : ""), Icon: Cpu })),
    { id:"heal",name:"Field injector",detail:`${e.meds} left · restore ${Math.round(stats.heal*100)}% HP`,Icon:HeartPulse },
    { id:"overclock",name:"Recover RAM",detail:"+3 RAM · take cover",Icon:Terminal },
  ];
  return <div className="rpg-combat"><div className="rpg-combat-topline"><span><i /> COMBAT LINK ACTIVE</span><span>ENCOUNTER {e.enemyIndex+1}/{mission.enemies.length} / TURN {e.turn+1}</span></div>
    <div className="rpg-battle-stage"><div className="rpg-runner-vitals"><small>YOUR VITALS</small><strong>{Math.ceil(state.health.currentHp)} <span>/ {maxHp} HP</span></strong><div className="rpg-bar hp"><i style={{width:`${state.health.currentHp/maxHp*100}%`}} /></div><p>{getItem(state.equippedGear.weapon ?? "")?.name ?? "Unarmed"}</p><span className="rpg-ram-label">{equippedDeck(state)?.name ?? "No cyberdeck equipped"} / RAM {e.ram}/{maxRam(state)}</span><div className="rpg-ram-pips">{Array.from({length:maxRam(state)},(_,i)=><i className={i<e.ram ? "filled" : ""} key={i}/>)}</div>{e.aimed && <b className="rpg-ready">AIMED SHOT READY</b>}</div>
      <svg className="rpg-enemy-silhouette" viewBox="0 0 220 240" role="img" aria-label="Hostile armored silhouette"><defs><linearGradient id="enemy-plate" x2="0" y2="1"><stop stopColor="#8f3548"/><stop offset="1" stopColor="#221e2b"/></linearGradient></defs><path d="M85 25 110 15 137 26 145 71 129 89 94 89 76 70Z" fill="url(#enemy-plate)" stroke="#ff6a7b"/><path d="M82 49 139 49 134 60 89 60Z" fill="#f4e16c"/><path d="M74 98 96 91 127 91 151 98 174 132 164 210 56 210 45 131Z" fill="url(#enemy-plate)" stroke="#be5264"/><path d="M80 103 110 122 143 103 132 155 89 155Z" fill="#432a39" stroke="#ff6a7b"/><path d="M48 111 27 131 20 191 44 202 64 149M170 112 193 131 202 191 176 202 159 149" fill="#332330" stroke="#93455a"/><path d="M58 218H165M10 8H42M10 8V40M210 8H178M210 8V40M10 232H42M10 232V200M210 232H178M210 232V200" fill="none" stroke="#ff6575"/><path d="M110 1V240M0 119H220" stroke="#ff657525" strokeDasharray="3 6"/></svg>
      <div className="rpg-enemy-vitals"><small>HOSTILE IDENTIFIED</small><h3>{mission.enemies[e.enemyIndex]}</h3><strong>{e.enemyHp} <span>/ {e.enemyMaxHp} HP</span></strong><div className="rpg-bar enemy"><i style={{width:`${e.enemyHp/e.enemyMaxHp*100}%`}} /></div><div className={`rpg-intent ${enemyIntent(state)==="Charged burst" ? "danger" : ""}`}><Target size={15}/><span>NEXT ATTACK<strong>{enemyIntent(state)}</strong></span></div></div>
    </div>{installedQuickhacks(state).length === 0 && <p className="rpg-choice-warning">No quickhacks installed. Return to the clinic, then open Main &gt; Character &gt; Quickhacks to equip a cyberdeck and install programs.</p>}<div className="rpg-tactics">{moves.map(({id,name,detail,Icon})=><button key={id} disabled={!canUseTactic(state,id)} onClick={()=>onUpdate(s=>performTactic(s,id))}><Icon size={20}/><span><strong>{name}</strong><small>{detail}</small></span></button>)}</div><div className="rpg-combat-log" role="log" aria-live="polite">{e.log.slice(-4).map((line,i)=><p key={`${e.turn}-${i}`}><ChevronRight size={12}/>{line}</p>)}</div><button className="rpg-text-button" onClick={()=>onUpdate(leaveRpgMission)}>Extract to clinic · resets this mission</button></div>;
}

export function BuildPanel({ state, onUpdate }: { state: GameState; onUpdate: Update }) {
  const stats = playerCombatStats(state);
  const field = tacticalStats(state);
  return <div className="rpg-build"><div className="rpg-build-heading"><div><p className="rpg-eyebrow">CHARACTER / LEVEL {state.rpg.level}</p><h2>Attributes & perks</h2><p>Attributes affect combat, equipment, upgrades and dialogue routes. Spend two attribute points and one perk point per level. Respec freely between missions.</p></div><div className="rpg-points"><strong>{state.rpg.attributePoints}<small>ATTRIBUTE POINTS</small></strong><strong>{state.rpg.perkPoints}<small>PERK POINTS</small></strong></div></div><div className="rpg-xp"><span>{state.rpg.level>=30 ? "MAX CHARACTER LEVEL" : `${state.rpg.xp} / ${rpgXpNeeded(state.rpg.level)} XP`}</span><div className="rpg-bar"><i style={{width:`${state.rpg.level>=30 ? 100 : state.rpg.xp/rpgXpNeeded(state.rpg.level)*100}%`}}/></div></div>
    {state.rpg.active && <p className="rpg-choice-warning">Attribute and perk changes are paused during a mission. Return to the clinic to respec.</p>}
    <div className="rpg-runner-stats" aria-label="Attribute-derived stats"><span>MAX HP<b>{stats.maxHp}</b></span><span>WEAPON DAMAGE<b>{stats.damage}</b></span><span>ARMOR<b>{stats.armor}</b></span><span>ATTACK INTERVAL<b>{(stats.attackSpeedMs / 1000).toFixed(2)}s</b></span><span>FIELD DAMAGE / HACK<b>{field.damage} / {field.hack}</b></span><span>RAM<b>{maxRam(state)}</b></span><span>UPGRADE LIMIT<b>+{Math.min(10, state.rpg.attributes.technical - 2 + (state.rpg.perks.tinkerer ? 2 : 0))}</b></span></div><p className="rpg-choice-warning">Attributes apply immediately, including before claiming your kit. Technical unlocks equipment upgrades; Tinkerer adds two upgrade levels. Gear and runner level also contribute to combat stats.</p><div className="rpg-attribute-grid">{attributeDefinitions.map(attribute=><article key={attribute.id}><div><Cpu size={21}/><strong>{state.rpg.attributes[attribute.id]}<small>/20</small></strong></div><h3>{attribute.name}</h3><p>{attribute.description}</p><p className="rpg-attribute-bonus">{attribute.bonusDescription}</p><small>{state.rpg.attributes[attribute.id] - 3} bonus points active</small><button disabled={Boolean(state.rpg.active) || state.rpg.attributePoints<1 || state.rpg.attributes[attribute.id]>=20} onClick={()=>onUpdate(s=>spendAttribute(s,attribute.id))}>+ Allocate point</button></article>)}</div><h3 className="rpg-subheading">Perks</h3><div className="rpg-perk-grid">{rpgPerks.map(perk=><button className={state.rpg.perks[perk.id] ? "owned" : ""} key={perk.id} disabled={Boolean(state.rpg.active) || state.rpg.perks[perk.id] || state.rpg.perkPoints<1 || state.rpg.attributes[perk.attribute]<perk.requirement} onClick={()=>onUpdate(s=>buyRpgPerk(s,perk.id))}><span>{state.rpg.perks[perk.id] ? <Check size={19}/> : <Sparkles size={19}/>}<small>{perk.attribute.toUpperCase()} {perk.requirement} / {state.rpg.perks[perk.id] ? "OWNED" : "1 POINT"}</small></span><strong>{perk.name}</strong><p>{perk.description}</p></button>)}</div><button className="rpg-text-button" disabled={Boolean(state.rpg.active)} onClick={()=>onUpdate(respecRpg)}>Refund all attributes and perks · free</button><p className="rpg-choice-warning">Resetting attributes unequips gear you no longer meet the requirements for. Items and upgrades stay in your inventory.</p></div>;
}

function FieldManual() {
  const entries = [
    ["01 / Make a name", "Claim your field kit, spend your starting build points, and answer Sable's call. Complete main jobs to open districts without idle skill grinding. Local gigs are repeatable sources of XP, credits, and components."],
    ["02 / Choose your approach", "Assault is always available. Cool unlocks stealth routes; Intelligence unlocks netrunner routes. Your starting lifepath opens special entrances. Failed attribute checks never block the main story."],
    ["03 / Read the threat", "Actions advance one turn. A charged burst is a warning to take cover or interrupt with Reboot Optics. Aim improves your next shot. RAM regenerates each turn; recovering RAM also provides cover."],
    ["04 / Keep moving", "Every deployment includes full health and two field injectors, with an extra injector from Field Medic. Health is shared with the rest of the game. Defeat allows a free retry. Missions wait while you're offline."],
    ["05 / Own the consequences", "Main-job decisions are permanent, alter your reputation or payout, and remain in your journal. The final job has three endings. Your earlier decisions determine the personal history carried into that ending."],
    ["06 / Work the city", "District services contain vendors, crafting, cyberware, companions, operations, and optional idle jobs. Mission rewards supply equipment and components directly. Starting idle work abandons an unfinished field mission."],
  ];
  return <div className="rpg-manual"><p className="rpg-eyebrow">FIELD MANUAL / READ BEFORE DEPLOYMENT</p><h2>The city won't wait. Your next turn will.</h2><div>{entries.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div>;
}
