import { MissionDebrief } from "../screens/Missions/MissionDebrief";
import { usePlayerNavigation, revealDetail } from "./PlayerNavigation";
import { TacticalEncounter } from "../screens/Missions/TacticalEncounter";
import { NextGoal } from "./NextGoal";
import { MainMenu, type CharacterTool } from "./MainMenu";
import { mainJobBalance } from "../data/mainJobBalance";
import { MobileSectionMenu } from "./MobileSectionMenu";
import { PerkTrees } from "./PerkTrees";
import { missionItemRewards, gigUniquePools, GIG_UNIQUE_CHANCE } from "../data/missionRewards";
import { gigRisks, gigPayout, heatCleanupCost, clearHeatWithFixer } from "../systems/rpgSystem";
import { equippedDeck, installedQuickhacks, quickhackRamCost } from "../systems/quickhackSystem";
import { NetworkHero } from "./NetworkHero";
import { playerCombatStats } from "../systems/formulas";
import { useEffect, useState, type ReactNode } from "react";
import { ArrowRight, ArrowUpRight, Backpack, TrendingUp, Check, ChevronRight, Cpu, Crosshair, HeartPulse, LockKeyhole, MapPin, MessageSquare, Radio, Shield, Skull, Sparkles, Target, Terminal, UserRound, Zap } from "lucide-react";
import { attributeDefinitions, rpgMissions, rpgSideGigs, rpgPerks, type RpgMission } from "../data/rpgCampaign";
import { districts } from "../data/districts";
import { getItem } from "../data/items";
import { calculateMaxHP } from "../systems/healthSystem";
import { approachRequirement, campaignEpilogue, fieldInjectorCount, buyRpgPerk, canUseTactic, chooseMissionApproach, claimFieldKit, enemyIntent, leaveRpgMission, mainChaptersCleared, maxRam, missionAvailable, missionById, performTactic, resolveRpgMission, respecRpg, retryRpgMission, rpgXpNeeded, spendAttribute, startRpgMission, tacticalStats } from "../systems/rpgSystem";
import type { GameState } from "../types";
import type { MissionApproach, TacticalAction, GigRisk } from "../rpgTypes";
import "./rpg.css";

type Update = (fn: (state: GameState) => GameState) => void;
const approachNames: Record<MissionApproach, string> = { assault: "Kick the door", ghost: "Go in quiet", netrunner: "Own the network", lifepath: "Use your connections" };
const endingNames: Record<string, string> = { free: "A City of Voices", own: "The New Sovereign", erase: "A Beautiful Silence" };

export type MainSection = "home" | "journal" | "character" | "progress" | "intel";

export function RpgHub({ state, onUpdate, onServices, page, onPage: setPage, inventoryNoticeCount = 0, onCharacterTool, children }: { state: GameState; onUpdate: Update; onServices: () => void; page: MainSection; onPage: (page: MainSection) => void; inventoryNoticeCount?: number; onCharacterTool?: (section: CharacterTool) => void; children?: ReactNode }) {
  const navigation = usePlayerNavigation();
  const [settlementBefore, setSettlementBefore] = useState<GameState | null>(null);
  const [gigs, setGigs] = useState(false);
  const [gigRisk, setGigRisk] = useState<GigRisk>("standard");
  const [selected, setSelected] = useState(() => rpgMissions.find(m => !state.rpg.completed[m.id])?.id ?? rpgMissions[7].id);
  const active = state.rpg.active;
  const mission = (active ? missionById(active.missionId) : missionById(selected)) ?? rpgMissions[0];
  const next = rpgMissions.find(m => !state.rpg.completed[m.id]);
  useEffect(() => { if (page === "journal" && !active) { setSelected(next?.id ?? rpgMissions[7].id); setGigs(false); } }, [page, next?.id]);
  useEffect(() => { if (page !== "journal") setSettlementBefore(null); }, [page]);
  const completed = mainChaptersCleared(state);
  const kit = state.rpg.starterClaimed;
  const selectedRisk = active?.gigRisk ?? ((state.rpg.completed[mission.id]?.clears ?? 0) >= gigRisks[gigRisk].clears ? gigRisk : "standard");
  if (page === "home") return <section className="rpg-shell" data-section="home" aria-label="Main / Afterimage RPG"><NextGoal state={state} /><MainMenu onOpen={setPage} onCharacter={section => { onCharacterTool?.(section); setPage("character"); }} activeMission={active ? mission.title : undefined} points={state.rpg.attributePoints + state.rpg.perkPoints} /></section>;
  if (page === "journal" && settlementBefore && !active) return <section className="rpg-shell" data-section="debrief"><MissionDebrief before={settlementBefore} after={state} onContinue={() => { const previous = missionById(settlementBefore.rpg.active!.missionId)!; setSettlementBefore(null); setGigs(Boolean(previous.sideGig)); setSelected(previous.sideGig ? previous.id : next?.id ?? previous.id); }} /></section>;
  return <section className="rpg-shell" data-section={page} aria-label="Main / Afterimage RPG">
    <NetworkHero title={["NEON", "AFTERIMAGE"]} eyebrow="YOUR NAME. YOUR RULES. YOUR CONSEQUENCES." description={<>Build a reputation. Bend the network.<br />Decide what survives the night.</>} status={<>PROFILE {String(state.rpg.level).padStart(2, "0")} <i /> STREET CRED {state.rpg.streetCred}</>} progress={{ label: "AFTERIMAGE / MAIN STORY", value: completed, maximum: 8, suffix: "/08", note: active ? "FIELD CONNECTION ACTIVE" : next ? `NEXT SIGNAL: ${next.fixer.toUpperCase()}` : "CAMPAIGN COMPLETE" }} actions={<><button className="rpg-primary" onClick={() => { setPage("journal"); setGigs(false); setSelected(next?.id ?? rpgMissions[7].id); }}>{active ? "Return to mission" : next ? "Track next lead" : "Review your ending"}<ArrowUpRight size={17} /></button><button className="rpg-text-button" onClick={() => setPage("character")}>Manage character <ChevronRight size={15} /></button></>} />
    <div className="mobile-main-navigation"><MobileSectionMenu label="Main sections" value={page} onChange={setPage} options={[{ id: "home", label: "All sections" }, { id: "journal", label: "Missions" }, { id: "character", label: "Character" }, { id: "progress", label: "Progress" }, { id: "intel", label: "Field manual" }]} /><button className="secondary-button" onClick={onServices}>District services <ArrowUpRight size={15} /></button></div>
    <div className="rpg-section-nav" role="tablist" aria-label="Runner network sections"><button onClick={() => setPage("home")}><Backpack size={16} />All sections</button>{([['journal','Missions',MessageSquare],['character','Character',UserRound],['progress','Progress',TrendingUp],['intel','Field manual',Terminal]] as const).map(([id,label,Icon]) => <button role="tab" aria-selected={page === id} key={id} onClick={() => setPage(id)} className={page === id ? "selected" : ""}><Icon size={16} />{label}{id === "character" && state.rpg.attributePoints + state.rpg.perkPoints > 0 && <b>{state.rpg.attributePoints + state.rpg.perkPoints}</b>}{id === "character" && inventoryNoticeCount > 0 && <b aria-label={`${inventoryNoticeCount} inventory updates`}>{inventoryNoticeCount} new</b>}</button>)}<button className="rpg-services" onClick={onServices}>District services <ArrowUpRight size={15} /></button></div>
    {page === "journal" && kit && !active && state.resources.heat > 0 && <div className="rpg-kit"><div><p className="rpg-eyebrow">FIXER SERVICES / HEAT {Math.ceil(state.resources.heat)}</p><p>Local gigs pay every clear and remove 15 Heat. For immediate cleanup, pay your fixer 10 credits per Heat.</p></div><button className="rpg-primary" disabled={Boolean(active) || state.resources.heat <= 0 || state.resources.credits < heatCleanupCost(state)} onClick={() => onUpdate(clearHeatWithFixer)}>Clear Heat / {heatCleanupCost(state)} credits</button></div>}
    {!kit && page === "journal" && <div className="rpg-kit"><Cpu size={28} /><div><h2>Your first call is waiting.</h2><p>Sable left a sidearm, armor, medicine, and a rechargeable quickhack deck. Claim the kit to begin. Existing equipment is kept.</p></div><button className="rpg-primary" onClick={() => { onUpdate(claimFieldKit); setPage("home"); }}>Claim field kit <ArrowRight size={16} /></button></div>}
    {page !== "journal" && page !== "intel" ? <div className="main-section-content">{children}</div> : page === "intel" ? <FieldManual /> : <div className="rpg-journal">
      <aside className="rpg-quest-list"><div className="rpg-list-heading"><span>YOUR JOURNAL</span><b>{completed}/8</b></div><div className="rpg-list-filters"><button className={!gigs ? "selected" : ""} onClick={() => { setGigs(false); if (!active) setSelected(next?.id ?? rpgMissions[7].id); }}>Main jobs</button><button className={gigs ? "selected" : ""} onClick={() => { setGigs(true); if (!active) { setSelected((rpgSideGigs.find(m => missionAvailable(state, m)) ?? rpgSideGigs[0]).id); setGigRisk("standard"); } }}>Local gigs</button></div>
        <label className="mobile-mission-picker">{gigs ? "Choose a local gig" : "Choose a main job"}<select value={mission.id} disabled={Boolean(active)} onChange={event => { setSelected(event.target.value); setGigRisk("standard"); }}>{(gigs ? rpgSideGigs : rpgMissions).map(entry => <option key={entry.id} value={entry.id}>{entry.act + 1}. {entry.title}</option>)}</select></label>
        {(gigs ? rpgSideGigs : rpgMissions).map(m => {
          const done = state.rpg.completed[m.id], available = missionAvailable(state, m), current = m.id === mission.id;
          return <button key={m.id} className={`rpg-quest ${current ? "selected" : ""}`} onClick={() => { setSelected(m.id); setGigRisk("standard"); }} disabled={Boolean(active && active.missionId !== m.id)} aria-current={current ? "true" : undefined}>
            <span className="rpg-quest-number">{done && !m.sideGig ? <Check size={16} /> : !available && !done ? <LockKeyhole size={14} /> : String(m.act + 1).padStart(2,"0")}</span><span><small>{districts.find(d => d.id === m.district)?.name}</small><strong>{m.title}</strong><em>{done ? m.sideGig ? `${done.clears} completed / replayable` : "Completed" : available ? m.sideGig ? "Gig available" : "Lead available" : m.act === 0 ? "Claim your field kit" : `Finish ${rpgMissions[m.act - 1].title}`}</em></span><ChevronRight size={14} /></button>;
        })}
        <p className="rpg-list-note">Main jobs unlock the next district. Local gigs provide repeatable money and item rewards. Craft local gear and spend your attribute points before tackling the next main job.</p>
      </aside>
      <div className="rpg-mission-content"><div className="rpg-mission-heading"><p className="rpg-eyebrow">{mission.sideGig ? "FIXER GIG" : `MAIN JOB / ACT ${String(mission.act + 1).padStart(2,"0")}`}</p><h2>{mission.title}</h2><p>{mission.tagline}</p><span><MapPin size={13} />{mission.location}</span></div>
        {active?.phase === "combat" ? <TacticalEncounter state={state} mission={mission} onUpdate={onUpdate} /> : active?.phase === "failed" ? <div className="rpg-failed"><Skull size={42} /><h3>Flatlined. Not forgotten.</h3><p>Your fixer got you out. Retry with full health and fresh field injectors, or return to improve your equipment and attributes. No credits or equipment are lost.</p><div className="rpg-button-row"><button className="rpg-primary" onClick={() => onUpdate(retryRpgMission)}>Retry mission</button><button onClick={() => onUpdate(leaveRpgMission)}>Return to clinic</button></div></div> : active?.phase === "decision" ? <div className="rpg-decision"><div className="rpg-contact"><MessageSquare size={20} /><span>SECURE CALL / {mission.fixer.toUpperCase()}</span></div><h3>{mission.sideGig ? "Area clear. Collect your payout." : "Boss defeated. Finish the job."}</h3><p>{mission.reveal}</p><span className="rpg-choice-warning">{mission.sideGig ? "Confirm the extraction to collect your rewards." : "This decision is permanent for this save and recorded in your journal."}</span><div className="rpg-choices">{mission.choices.map(choice => <button key={choice.id} onClick={() => { setSettlementBefore(state); onUpdate(s => resolveRpgMission(s, choice.id)); revealDetail(".mission-debrief"); }}><span><strong>{choice.label}</strong><small>{choice.detail}</small></span><ArrowUpRight size={20} /></button>)}</div></div> : <>
          <div className="rpg-contact"><span className="rpg-contact-avatar">{mission.fixer.split(" ").map(n => n[0]).join("")}</span><div><small>INCOMING / ENCRYPTED</small><strong>{mission.fixer}</strong></div><Radio size={18} /></div><p className="rpg-briefing">“{mission.briefing}”</p>
          {state.rpg.completed[mission.id] && !active && <div className="rpg-aftermath"><Check size={19} /><div><h3>{mission.act === 7 && !mission.sideGig && state.rpg.ending ? endingNames[state.rpg.ending] : "Job closed"}</h3><p>{mission.choices.find(c => c.id === state.rpg.completed[mission.id].outcome)?.response}</p><small>Approach: {approachNames[state.rpg.completed[mission.id].approach]}</small>{mission.act === 7 && !mission.sideGig && <p>{rpgMissions.slice(0,7).filter(m => state.rpg.completed[m.id]?.outcome === "protect").length} of your 7 earlier decisions protected the people caught in the program. {campaignEpilogue(state)}</p>}</div></div>}
          <div className="rpg-objective"><Target size={19} /><div><small>OBJECTIVE</small><strong>{mission.objective}</strong>{!mission.sideGig && <p>{mission.enemies.length - 1} patrols, then {mission.enemies[mission.enemies.length - 1]}. Health and injectors carry between fights. Prepare locally crafted gear, such as {getItem(mainJobBalance[mission.district].weapon)?.name} and {getItem(mainJobBalance[mission.district].armor)?.name}, or comparable equipment.</p>}</div></div>
          {mission.sideGig && !active && <div className="stack"><p className="rpg-eyebrow">REPLAYABLE GIG / {state.rpg.completed[mission.id]?.clears ?? 0} CLEARS</p><div className="rpg-button-row">{(Object.keys(gigRisks) as GigRisk[]).map(risk => <button key={risk} aria-pressed={selectedRisk === risk} disabled={(state.rpg.completed[mission.id]?.clears ?? 0) < gigRisks[risk].clears} onClick={() => setGigRisk(risk)}>{gigRisks[risk].label} / {gigRisks[risk].payout}x credits{gigRisks[risk].clears > 0 ? " / " + gigRisks[risk].clears + " clears required" : ""}</button>)}</div><p className="muted">Enemy health x{gigRisks[selectedRisk].health}; enemy damage x{gigRisks[selectedRisk].damage}. Supplies and XP stay the same. Main jobs alone advance the Afterimage story.</p></div>}<div className="rpg-reward-strip"><span>PAYOUT <b>€$ {gigPayout(mission, selectedRisk).toLocaleString()}</b></span><span>CHARACTER XP <b>{state.rpg.completed[mission.id] && mission.sideGig ? Math.round(mission.xp * .5) : mission.xp}</b></span><span>SUPPLIES <b>{mission.sideGig ? "Materials + rare gear chance" : "Crafting supplies"}</b></span></div><div className="rpg-loot-preview"><p className="rpg-eyebrow">REWARD DETAILS</p>{mission.sideGig && <p className="fine">Rare unique gear: {GIG_UNIQUE_CHANCE * 100}% chance per clear for one item, chosen equally from {gigUniquePools[mission.district].map(id => getItem(id)?.name ?? id).join(", ")}. No guaranteed gear. Craft equipment in District services &gt; Crafting.</p>}<div className="runner-guide-tags">{Object.entries(missionItemRewards(mission, state.rpg.completed[mission.id]?.clears ?? 0)).map(([id, quantity]) => <span key={id}>{getItem(id)?.name ?? id} ×{quantity}</span>)}</div></div>
          {active?.phase === "briefing" ? <><h3 className="rpg-subheading">Choose your way in</h3><div className="rpg-approaches">{(["assault","ghost","netrunner","lifepath"] as MissionApproach[]).map(approach => { const req = approachRequirement(state,mission,approach); return <button key={approach} disabled={!req.met} onClick={() => onUpdate(s => chooseMissionApproach(s, approach))}><span>{approach === "netrunner" ? <Cpu size={21} /> : approach === "ghost" ? <Shield size={21} /> : approach === "lifepath" ? <MessageSquare size={21} /> : <Crosshair size={21} />}</span><strong>{approachNames[approach]}</strong><small>{req.label}</small>{approach === "lifepath" && <small>{mission.pathLine}</small>}</button>; })}</div><button className="rpg-text-button" onClick={() => onUpdate(leaveRpgMission)}>Leave briefing and prepare</button></> : <button className="rpg-primary rpg-start" disabled={!missionAvailable(state,mission)} onClick={() => onUpdate(s => startRpgMission(s,mission.id,selectedRisk))}>{state.rpg.completed[mission.id] && !mission.sideGig ? "Chapter completed" : !kit ? "Claim the field kit first" : missionAvailable(state,mission) ? mission.sideGig ? "Accept gig" : "Answer the call" : "Complete the previous main job"}<ArrowUpRight size={19} /></button>}
          <div className="mission-preparation"><strong>Before you deploy</strong><p>{state.equippedGear.weapon && state.equippedGear.chest ? "Weapon and armor equipped." : "Equip a weapon and chest armor from your inventory."} {state.rpg.attributePoints + state.rpg.perkPoints > 0 ? "You have unspent attribute or perk points." : "Your points are allocated."}</p><div className="journey-actions"><button className="secondary-button" onClick={() => navigation.openCharacter?.("gear")}>Review equipment</button><button className="secondary-button" onClick={() => navigation.openCharacter?.("attributes")}>Attributes &amp; perks</button><button className="secondary-button" onClick={() => navigation.openCrafting?.()}>Craft upgrades</button></div></div><p className="rpg-mission-note">Fixer support restores health before deployment and supplies {fieldInjectorCount(state)} field injectors. Starting a mission stops idle work. Combat advances only when you choose an action.</p>
        </>}
      </div>
    </div>}
  </section>;
}

export function BuildPanel({ state, onUpdate }: { state: GameState; onUpdate: Update }) {
  const stats = playerCombatStats(state);
  const field = tacticalStats(state);
  return <div className="rpg-build"><div className="rpg-build-heading"><div><p className="rpg-eyebrow">CHARACTER / LEVEL {state.rpg.level}</p><h2>Attributes & perks</h2><p>Attributes affect combat, equipment, upgrades and dialogue routes. Spend two attribute points and one perk point per level. Respec freely between missions.</p></div><div className="rpg-points"><strong>{state.rpg.attributePoints}<small>ATTRIBUTE POINTS</small></strong><strong>{state.rpg.perkPoints}<small>PERK POINTS</small></strong></div></div><div className="rpg-xp"><span>{state.rpg.level>=30 ? "MAX CHARACTER LEVEL" : `${state.rpg.xp} / ${rpgXpNeeded(state.rpg.level)} XP`}</span><div className="rpg-bar"><i style={{width:`${state.rpg.level>=30 ? 100 : state.rpg.xp/rpgXpNeeded(state.rpg.level)*100}%`}}/></div></div>
    {state.rpg.active && <p className="rpg-choice-warning">Attribute and perk changes are paused during a mission. Return to the clinic to respec.</p>}
<div className="rpg-runner-stats" aria-label="Attribute-derived stats"><span>MAX HP<b>{stats.maxHp}</b></span><span>WEAPON DAMAGE<b>{stats.damage}</b></span><span>ARMOR<b>{stats.armor}</b></span><span>ATTACK INTERVAL<b>{(stats.attackSpeedMs / 1000).toFixed(2)}s</b></span><span>FIELD DAMAGE / HACK<b>{field.damage} / {field.hack}</b></span><span>RAM<b>{maxRam(state)}</b></span><span>UPGRADE LIMIT<b>+{Math.min(10, state.rpg.attributes.technical - 2 + (state.rpg.perks.tinkerer ? 2 : 0))}</b></span></div><p className="rpg-choice-warning">Attributes apply immediately, including before claiming your kit. Technical unlocks equipment upgrades; Tinkerer adds two upgrade levels. Gear and runner level also contribute to combat stats.</p><div className="rpg-attribute-grid">{attributeDefinitions.map(attribute=><article key={attribute.id}><div><Cpu size={21}/><strong>{state.rpg.attributes[attribute.id]}<small>/20</small></strong></div><h3>{attribute.name}</h3><p>{attribute.description}</p><p className="rpg-attribute-bonus">{attribute.bonusDescription}</p><small>{state.rpg.attributes[attribute.id] - 3} bonus points active</small><button disabled={Boolean(state.rpg.active) || state.rpg.attributePoints<1 || state.rpg.attributes[attribute.id]>=20} onClick={()=>onUpdate(s=>spendAttribute(s,attribute.id))}>+ Allocate point</button></article>)}</div><PerkTrees state={state} onUpdate={onUpdate} /><button className="rpg-text-button" disabled={Boolean(state.rpg.active)} onClick={()=>onUpdate(respecRpg)}>Refund all attributes and perks · free</button><p className="rpg-choice-warning">Resetting attributes unequips gear you no longer meet the requirements for. Items and upgrades stay in your inventory.</p></div>;
}

function FieldManual() {
  const entries = [
    ["01 / Make a name", "Claim your field kit, spend your starting attribute and perk points, and answer Sable's call. Craft and upgrade district gear, then complete main jobs to open the next district. Each main job ends in a boss fight. Local gigs are repeatable sources of XP, credits, and components."],
    ["02 / Choose your approach", "Assault is always available. Cool unlocks stealth routes; Intelligence unlocks netrunner routes. Your starting lifepath opens special entrances. Failed attribute checks never block the main story."],
    ["03 / Read the threat", "Actions advance one turn. A charged burst is a warning to take cover or interrupt with Reboot Optics. Aim improves your next shot. RAM regenerates each turn; recovering RAM also provides cover."],
    ["04 / Keep moving", "Every deployment includes full health and two field injectors, with an extra injector from Field Medic. Health is shared with the rest of the game. Defeat allows a free retry. Missions wait while you're offline."],
    ["05 / Own the consequences", "Main-job decisions are permanent, alter your reputation or payout, and remain in your journal. The final job has three endings. Your earlier decisions determine the personal history carried into that ending."],
    ["06 / Work the city", "District services contain vendors, crafting, cyberware, companions, and optional training. Main jobs supply crafting materials; local gigs fund upgrades and rarely drop unique gear. Starting idle work abandons an unfinished field mission."],
  ];
  return <div className="rpg-manual"><p className="rpg-eyebrow">FIELD MANUAL / READ BEFORE DEPLOYMENT</p><h2>The city won't wait. Your next turn will.</h2><div>{entries.map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div>;
}
