import { encounterArtwork } from "../../data/districtPresentation";
import { Crosshair, Target, Shield, Cpu, HeartPulse, Terminal, ChevronRight } from "lucide-react";
import { getItem } from "../../data/items";
import type { RpgMission } from "../../data/rpgCampaign";
import { calculateMaxHP } from "../../systems/healthSystem";
import { equippedDeck, installedQuickhacks, quickhackRamCost } from "../../systems/quickhackSystem";
import { tacticalStats, canUseTactic, enemyIntent, maxRam, performTactic, leaveRpgMission } from "../../systems/rpgSystem";
import type { GameState } from "../../types";
import type { TacticalAction } from "../../rpgTypes";
type Update = (fn: (state: GameState) => GameState) => void;
export function TacticalEncounter({ state, mission, onUpdate }: { state: GameState; mission: RpgMission; onUpdate: Update }) {
  const e = state.rpg.active!, stats = tacticalStats(state), maxHp = calculateMaxHP(state);
  const boss = !mission.sideGig && e.enemyIndex === mission.enemies.length - 1;
  const art = encounterArtwork[mission.id + ":" + e.enemyIndex];
  const intent = enemyIntent(state);
  const moves: Array<{ id: TacticalAction; name: string; detail: string; Icon: typeof Target }> = [
    { id:"attack",name:e.aimed ? "Aimed shot" : "Fire weapon", detail:`${stats.damage} base damage${e.aimed ? " · aim bonus ready" : ""}`,Icon:Crosshair },
    { id:"aim",name:"Aim from cover",detail:"Prime next shot · reduce incoming damage",Icon:Target },
    { id:"cover",name:"Take cover",detail:"Absorb a burst · regenerate RAM",Icon:Shield },
    ...installedQuickhacks(state).map(h => ({ id: `quickhack:${h.id}` as TacticalAction, name: h.name, detail: quickhackRamCost(state, h) + " RAM / " + Math.round(stats.hack * h.multiplier * (e.approach === "netrunner" ? 1.35 : 1)) + " damage / " + h.rarity + (h.effect ? " / " + h.effect : "") + (h.interrupt ? " / interrupts" : ""), Icon: Cpu })),
    { id:"heal",name:"Field injector",detail:`${e.meds} left · restore ${Math.round(stats.heal*100)}% HP`,Icon:HeartPulse },
    { id:"overclock",name:"Recover RAM",detail:"+3 RAM · take cover",Icon:Terminal },
  ];
  return <div className={`rpg-combat ${boss ? "boss-encounter" : ""}`}><ol className="encounter-track" aria-label="Fight sequence">{mission.enemies.map((name, index) => <li key={index} aria-current={index === e.enemyIndex ? "step" : undefined} className={index < e.enemyIndex ? "cleared" : index === e.enemyIndex ? "current" : ""}><span>{index < e.enemyIndex ? "Cleared" : !mission.sideGig && index === mission.enemies.length - 1 ? "Boss" : "Fight " + (index + 1)}</span><small>{name}</small></li>)}</ol>{boss && <div className="boss-banner">FINAL ENCOUNTER / {mission.enemies[e.enemyIndex]}</div>}<div className="rpg-combat-topline"><span><i /> COMBAT LINK ACTIVE</span><span>ENCOUNTER {e.enemyIndex+1}/{mission.enemies.length} / TURN {e.turn+1}</span></div>
    <div className={`combat-guidance ${intent === "Charged burst" ? "charged" : ""}`} role="status"><strong>{intent === "Charged burst" ? "Charged burst incoming" : "Your turn / " + intent}</strong><p>{intent === "Charged burst" ? "Take cover or interrupt with a quickhack to reduce this threat." : "Each action advances one turn. Cover reduces the next hit; aim prepares a stronger shot."}</p></div><div className="rpg-battle-stage"><div className="rpg-runner-vitals"><small>YOUR VITALS</small><strong>{Math.ceil(state.health.currentHp)} <span>/ {maxHp} HP</span></strong><div className="rpg-bar hp" role="progressbar" aria-label="Your health" aria-valuenow={Math.ceil(state.health.currentHp)} aria-valuemin={0} aria-valuemax={maxHp}><i style={{width:`${state.health.currentHp/maxHp*100}%`}} /></div><p>{getItem(state.equippedGear.weapon ?? "")?.name ?? "Unarmed"}</p><span className="rpg-ram-label">{equippedDeck(state)?.name ?? "No cyberdeck equipped"} / RAM {e.ram}/{maxRam(state)}</span><div className="rpg-ram-pips" role="meter" aria-label="Available RAM" aria-valuenow={e.ram} aria-valuemin={0} aria-valuemax={maxRam(state)}>{Array.from({length:maxRam(state)},(_,i)=><i className={i<e.ram ? "filled" : ""} key={i}/>)}</div>{e.aimed && <b className="rpg-ready">AIMED SHOT READY</b>}</div>
      {art ? <img className="rpg-enemy-silhouette encounter-art" src={art.src} alt={art.alt} /> : <svg className="rpg-enemy-silhouette" viewBox="0 0 220 240" role="img" aria-label="Hostile armored silhouette"><defs><linearGradient id="enemy-plate" x2="0" y2="1"><stop stopColor="#8f3548"/><stop offset="1" stopColor="#221e2b"/></linearGradient></defs><path d="M85 25 110 15 137 26 145 71 129 89 94 89 76 70Z" fill="url(#enemy-plate)" stroke="#ff6a7b"/><path d="M82 49 139 49 134 60 89 60Z" fill="#f4e16c"/><path d="M74 98 96 91 127 91 151 98 174 132 164 210 56 210 45 131Z" fill="url(#enemy-plate)" stroke="#be5264"/><path d="M80 103 110 122 143 103 132 155 89 155Z" fill="#432a39" stroke="#ff6a7b"/><path d="M48 111 27 131 20 191 44 202 64 149M170 112 193 131 202 191 176 202 159 149" fill="#332330" stroke="#93455a"/><path d="M58 218H165M10 8H42M10 8V40M210 8H178M210 8V40M10 232H42M10 232V200M210 232H178M210 232V200" fill="none" stroke="#ff6575"/><path d="M110 1V240M0 119H220" stroke="#ff657525" strokeDasharray="3 6"/></svg>}
      <div className="rpg-enemy-vitals"><small>{!mission.sideGig && e.enemyIndex === mission.enemies.length - 1 ? "DISTRICT BOSS" : "HOSTILE IDENTIFIED"}</small><h3>{mission.enemies[e.enemyIndex]}</h3>{(e.burnTurns ?? 0) > 0 && <p className="rpg-ready">OVERHEAT: {e.burnDamage} damage / {e.burnTurns} turns</p>}{(e.weakenTurns ?? 0) > 0 && <p className="rpg-ready">MOVEMENT DISABLED: -{Math.round((e.weaken ?? 0) * 100)}% damage / {e.weakenTurns} turns</p>}<strong>{e.enemyHp} <span>/ {e.enemyMaxHp} HP</span></strong><div className="rpg-bar enemy" role="progressbar" aria-label="Enemy health" aria-valuenow={e.enemyHp} aria-valuemin={0} aria-valuemax={e.enemyMaxHp}><i style={{width:`${e.enemyHp/e.enemyMaxHp*100}%`}} /></div><div className={`rpg-intent ${enemyIntent(state)==="Charged burst" ? "danger" : ""}`}><Target size={15}/><span>NEXT ATTACK<strong>{enemyIntent(state)}</strong></span></div></div>
    </div>{installedQuickhacks(state).length === 0 && <p className="rpg-choice-warning">No quickhacks installed. Return to the clinic, then open Main &gt; Character &gt; Quickhacks to equip a cyberdeck and install programs.</p>}<div className="rpg-tactics">{moves.map(({id,name,detail,Icon})=><button key={id} disabled={!canUseTactic(state,id)} onClick={()=>onUpdate(s=>performTactic(s,id))}><Icon size={20}/><span><strong>{name}</strong><small>{detail}</small>{!canUseTactic(state,id) && <small className="tactic-unavailable">{id === "heal" ? e.meds === 0 ? "No injectors left" : "Health is already full" : id === "overclock" ? "RAM is already full" : "Not enough RAM - take cover to recover"}</small>}</span></button>)}</div><div className="rpg-combat-log" role="log" aria-label="Recent combat events" aria-live="polite">{e.log.slice(-4).map((line,i)=><p className={/Enemy fire|Charged burst:/.test(line) ? "feedback-damage" : /restored|neutralized|interrupted/.test(line) ? "feedback-success" : ""} key={`${e.turn}-${i}`}><ChevronRight size={12}/>{line}</p>)}</div><button className="rpg-text-button" onClick={()=>onUpdate(leaveRpgMission)}>Extract to clinic · resets this mission</button></div>;
}

